apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsiforce-runtime-proxies.fullname" . }}-secret
type: Opaque
stringData:
  PROXY_CONTROL_TOKEN: {{ .Values.config.proxyControlToken | quote }}
