nameOverride: ""
fullnameOverride: ""

imagePullSecrets:
  - name: ghcr-pull-secret

storage:
  type: hostPath
  className: cephfs
  size: 10Gi
  hostPath: /tmp/opsiforce-data

agent:
  image:
    repository: ghcr.io/simadevelopment/opsiforce
    tag: agent
    pullPolicy: Always
  port: 4096
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi
  nodeSelector: {}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: cfke.io/region
                operator: In
                values:
                  - northamerica
              - key: cfke.io/subregion
                operator: In
                values:
                  - east
              - key: node.kubernetes.io/instance-type
                operator: NotIn
                values:
                  - cpx11
                  - cpx21
                  - cpx22
                  - cpx32
                  - cpx31
                  - ccx13
                  - ccx23
                  - cx23
                  - cx33
  tolerations: []

warmPool:
  size: 0

timeout:
  idleMinutes: 30
