yarnPath: .yarn/releases/yarn-4.17.0.cjs

nodeLinker: pnp

enableScripts: true

approvedGitRepositories:
  - "https://github.com/anomalyco/ghostty-web.git"

packageExtensions:
  "@tanstack/router-devtools-core@*":
    dependencies:
      "@tanstack/router-core": "*"
  drizzle-kit@*:
    peerDependencies:
      drizzle-orm: "*"
    dependencies:
      postgres: "*"
  "@bull-board/api@*":
    peerDependencies:
      bullmq: "*"
    dependencies:
      "@bull-board/ui": "6.21.2"
