DATABASE_URL=postgres://admin:dbpass1@localhost:5435/opsiforce
ANTHROPIC_API_KEY=sk-ant-placeholder
BIFROST_ADMIN_USERNAME=opsiforce-admin
BIFROST_ADMIN_PASSWORD=opsiforce-local-admin
BIFROST_ENCRYPTION_KEY=0123456789abcdef0123456789abcdef
BIFROST_POSTGRES_PASSWORD=dbpass1
