apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opsiforce-bifrost.fullname" . }}
  labels:
    {{- include "opsiforce-bifrost.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "opsiforce-bifrost.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        karpenter.sh/do-not-disrupt: "true"
      labels:
        {{- include "opsiforce-bifrost.selectorLabels" . | nindent 8 }}
        app: {{ include "opsiforce-bifrost.fullname" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: bifrost
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
          envFrom:
            - secretRef:
                name: {{ include "opsiforce-bifrost.fullname" . }}-secret
          env:
            - name: APP_PORT
              value: {{ .Values.containerPort | quote }}
            - name: APP_HOST
              value: "0.0.0.0"
            - name: LOG_LEVEL
              value: "info"
            - name: LOG_STYLE
              value: "json"
          volumeMounts:
            - name: config
              mountPath: /app/config.json
              subPath: config.json
              readOnly: true
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "opsiforce-bifrost.fullname" . }}-config
