apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsiforce-bifrost.fullname" . }}-secret
  labels:
    {{- include "opsiforce-bifrost.labels" . | nindent 4 }}
type: Opaque
stringData:
  OPENAI_API_KEY: {{ .Values.config.openaiApiKey | quote }}
  MASTER_KEY: {{ .Values.config.masterKey | quote }}
  DATABASE_URL: {{ .Values.config.databaseUrl | quote }}
