const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');
const base=process.env.FILES_BASE, upstream=process.env.FILES_UPSTREAM || base;
const project=process.env.FILES_PROJECT_ID, folder=process.env.FILES_FOLDER;
if(!base || !project || !folder) throw new Error('Set FILES_BASE, FILES_PROJECT_ID and FILES_FOLDER for a test project with app source and no exported files.');
(async()=>{const browser=await chromium.launch({headless:true,timeout:20000,args:['--disable-gpu'],...(process.env.CHROME_PATH ? {executablePath:process.env.CHROME_PATH} : {})});
try{const page=await browser.newPage({viewport:{width:1600,height:1000}});page.setDefaultTimeout(12000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/api/**',async route=>{
  const req=route.request(),u=new URL(req.url());
  if(req.method()==='PATCH' && u.pathname.endsWith('/session')) return route.fulfill({json:{ok:true}});
  if(req.method()!=='GET' && u.pathname!=='/api/users/me') return route.abort();
  return route.continue({url:upstream+u.pathname+u.search});
});
await page.goto(base+'/projects/'+project);
await page.getByRole('tab',{name:'文件',exact:true}).click();
await page.getByText(folder,{exact:true}).waitFor({timeout:5000});
await page.getByRole('button',{name:/^输出文件/}).click();
await page.getByRole('button',{name:'查看项目文件',exact:true}).waitFor();
await page.getByRole('tab',{name:'对话',exact:true}).click();await page.getByRole('tab',{name:'文件',exact:true}).click();
assert.equal(await page.getByRole('button',{name:/^输出文件/}).getAttribute('aria-pressed'),'true','refresh preserves a manually selected category');
await page.getByRole('button',{name:'查看项目文件',exact:true}).click();
await page.getByText(folder,{exact:true}).click();
await page.getByText('main.py',{exact:true}).waitFor();
await page.getByText('requirements.txt',{exact:true}).waitFor();
await page.getByText('static',{exact:true}).click();
await page.getByText('index.html',{exact:true}).waitFor();
await page.screenshot({path:process.env.FILES_SCREENSHOT || '/tmp/opsiforce-project-files.png',fullPage:true});
assert.deepEqual(errors,[]);console.log('PASS: opening Files immediately exposes the existing project folder and its Python and HTML files');
}finally{await browser.close()}})().catch(e=>{console.error(e.message);process.exit(1)});
