nodeLinker: pnp
pnpEnableEsmLoader: true

enableGlobalCache: false
enableImmutableInstalls: false

packageExtensions:
  "framer-motion@*":
    dependencies:
      "@emotion/is-prop-valid": "*"

plugins:
  - path: .yarn/plugins/reload-frontend-vite.cjs
