apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opsiforce-proxy.fullname" . }}
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      client_max_body_size 5m;

      client_header_buffer_size 128k;
      large_client_header_buffers 4 128k;

      server {
          listen       80;
          server_name  _;
          location /api/gateway {
            return 403;
          }
          location /api/proxy {
            proxy_http_version 1.1;
            proxy_buffering off;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_read_timeout 86400s;
            proxy_pass {{ .Values.proxy.agentService }};
          }
          location /api {
            proxy_http_version 1.1;
            proxy_buffering off;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_read_timeout 86400s;
            proxy_pass {{ .Values.proxy.backendService }};
          }
          location / {
            proxy_pass {{ .Values.proxy.frontendService }};
          }
      }
    }
