{{- if .Values.ingressRoute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "opsiforce-proxy.fullname" . }}-db
  labels:
    {{- include "opsiforce-proxy.labels" . | nindent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "*.{{ .Values.dbProxy.appsHostname }}"
    external-dns.alpha.kubernetes.io/target: {{ .Values.ingressRoute.traefikTarget }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostRegexp(`[a-f0-9-]+\.{{ .Values.dbProxy.appsHostname | replace "." "\\." }}`)
      kind: Rule
      services:
        - name: {{ include "opsiforce-proxy.fullname" . }}
          port: 4180
  {{- if .Values.ingressRoute.certResolver }}
  tls:
    certResolver: {{ .Values.ingressRoute.certResolver }}
    domains:
      - main: "*.{{ .Values.dbProxy.appsHostname }}"
  {{- end }}
{{- end }}
