{{- if .Values.ingressRoute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "opsiforce-proxy.fullname" . }}-webapp
  labels:
    {{- include "opsiforce-proxy.labels" . | nindent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "*.{{ .Values.appProxy.appsHostname }}{{- if .Values.appProxy.previewAppsHostname }},*.{{ .Values.appProxy.previewAppsHostname }}{{- end }}"
    external-dns.alpha.kubernetes.io/target: {{ .Values.ingressRoute.traefikTarget }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostRegexp(`[a-f0-9-]+\.{{ .Values.appProxy.appsHostname | replace "." "\\." }}`)
      kind: Rule
      services:
        - name: {{ .Values.appProxy.backendService }}
          port: {{ .Values.appProxy.backendPort }}
    {{- if .Values.appProxy.previewAppsHostname }}
    - match: HostRegexp(`[a-f0-9-]+\.{{ .Values.appProxy.previewAppsHostname | replace "." "\\." }}`)
      kind: Rule
      services:
        - name: {{ include "opsiforce-proxy.fullname" . }}
          port: 4180
    {{- end }}
  {{- if .Values.ingressRoute.certResolver }}
  tls:
    certResolver: {{ .Values.ingressRoute.certResolver }}
    domains:
      - main: "*.{{ .Values.appProxy.appsHostname }}"
      {{- if .Values.appProxy.previewAppsHostname }}
      - main: "*.{{ .Values.appProxy.previewAppsHostname }}"
      {{- end }}
  {{- end }}
{{- end }}
