apiVersion: v1
kind: Service
metadata:
  name: {{ include "opsiforce-proxy.fullname" . }}
  annotations:
    service.kubernetes.io/topology-mode: "Auto"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 4180
      targetPort: 4180
      protocol: TCP
      name: http
  selector:
    app: {{ include "opsiforce-proxy.fullname" . }}
