apiVersion: v1
kind: Service
metadata:
  name: {{ include "opsiforce-proxy.fullname" . }}
  annotations:
    service.kubernetes.io/topology-mode: "Auto"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ include "opsiforce-proxy.proxyPort" . }}
      targetPort: {{ include "opsiforce-proxy.proxyPort" . }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "opsiforce-proxy.fullname" . }}
