FROM node:24-alpine AS builder

WORKDIR /app

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn/releases .yarn/releases

COPY packages/opsiforce/backend/ ./packages/opsiforce/backend/

WORKDIR packages/opsiforce/backend
RUN yarn install
RUN yarn run build

FROM node:24-alpine AS server

WORKDIR /app

COPY --from=builder /app/.yarn ./.yarn
COPY --from=builder /app/.pnp.* ./
COPY package.json yarn.lock .yarnrc.yml ./

COPY --from=builder /app/packages/opsiforce/backend/dist ./packages/opsiforce/backend/dist
COPY --from=builder /app/packages/opsiforce/backend/package.json ./packages/opsiforce/backend/package.json

WORKDIR /app/packages/opsiforce/backend/

ENV NODE_ENV="production"

RUN yarn workspaces focus --all --production

EXPOSE 3001

CMD ["yarn", "run", "start"]
