FROM node:24.18.0-alpine

ARG PKG_PREFIX=

RUN apk add --no-cache python3 make g++ git

WORKDIR /app

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn/releases .yarn/releases

COPY ${PKG_PREFIX}backend/ ./${PKG_PREFIX}backend/
COPY ${PKG_PREFIX}agent-config/agent-image-version.json ./${PKG_PREFIX}agent-config/agent-image-version.json
COPY ${PKG_PREFIX}agent-config/agents.json ./${PKG_PREFIX}agent-config/agents.json
COPY ${PKG_PREFIX}agent-config/priv*/agents.json ./${PKG_PREFIX}agent-config/private/

RUN yarn workspaces focus @opsiforce/backend

WORKDIR /app/${PKG_PREFIX}backend

ENV NODE_OPTIONS="--max-http-header-size=128000"
EXPOSE 3001 9229

CMD ["yarn", "nest", "start", "--watch", "--debug", "0.0.0.0:9229"]
