FROM node:24.14-alpine AS builder

RUN apk add --no-cache python3 make g++

WORKDIR /app

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn/releases .yarn/releases

COPY packages/opsiforce/backend/ ./packages/opsiforce/backend/

WORKDIR packages/opsiforce/backend
RUN yarn install
RUN yarn run build
RUN yarn run db:generate

FROM node:24.14-alpine AS server

WORKDIR /app

COPY --from=builder /app/.yarn ./.yarn
COPY --from=builder /app/.pnp.* ./
COPY package.json yarn.lock .yarnrc.yml ./

COPY --from=builder /app/packages/opsiforce/backend/dist ./packages/opsiforce/backend/dist
COPY --from=builder /app/packages/opsiforce/backend/db ./packages/opsiforce/backend/db
COPY --from=builder /app/packages/opsiforce/backend/package.json ./packages/opsiforce/backend/package.json
COPY packages/opsiforce/backend/platform-version.json ./packages/opsiforce/backend/platform-version.json
COPY packages/opsiforce/agent-config/agent-image-version.json ./packages/opsiforce/agent-config/agent-image-version.json
COPY packages/opsiforce/agent-config/agents.json ./packages/opsiforce/agent-config/agents.json

WORKDIR /app/packages/opsiforce/backend/

ENV NODE_ENV="production"
ENV NODE_OPTIONS="--max-http-header-size=128000"

RUN apk add --no-cache python3 make g++ && \
    yarn workspaces focus --all --production && \
    apk del python3 make g++

EXPOSE 3001

CMD ["yarn", "run", "start"]
