FROM node:24-alpine

WORKDIR /app

ENV NODE_OPTIONS="--max-http-header-size=128000"

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn ./.yarn
COPY packages/opsiforce/frontend ./packages/opsiforce/frontend

RUN yarn workspaces focus --all

WORKDIR /app/packages/opsiforce/frontend

ARG VITE_WEBAPP_DOMAIN=localhost:3002
ENV VITE_WEBAPP_DOMAIN=$VITE_WEBAPP_DOMAIN
ARG VITE_VSCODE_DOMAIN=localhost:3003
ENV VITE_VSCODE_DOMAIN=$VITE_VSCODE_DOMAIN

RUN yarn build

EXPOSE 80

CMD ["yarn", "dlx", "serve", "-s", "dist", "-l", "80"]
