apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opsiforce-frontend.fullname" . }}
  labels:
    app: {{ include "opsiforce-frontend.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "opsiforce-frontend.fullname" . }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: {{ include "opsiforce-frontend.fullname" . }}
    spec:
      containers:
        - name: opsiforce-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          lifecycle:
            preStop:
              exec:
                command: [ sh, -c, "sleep 30" ]
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
          resources:
            requests:
              cpu: {{ .Values.frontend.resources.requests.cpu }}
              memory: {{ .Values.frontend.resources.requests.memory }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.containerPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.containerPort }}
