{{- if or .Values.config.openaiApiKey .Values.config.bifrostAdminUsername .Values.config.bifrostAdminPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsiforce-backend.fullname" . }}-secret
  labels:
    {{- include "opsiforce-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.config.openaiApiKey }}
  OPENAI_API_KEY: {{ .Values.config.openaiApiKey | quote }}
  {{- end }}
  {{- if .Values.config.bifrostAdminUsername }}
  BIFROST_ADMIN_USERNAME: {{ .Values.config.bifrostAdminUsername | quote }}
  {{- end }}
  {{- if .Values.config.bifrostAdminPassword }}
  BIFROST_ADMIN_PASSWORD: {{ .Values.config.bifrostAdminPassword | quote }}
  {{- end }}
{{- end }}
