apiVersion: v1
kind: Service
metadata:
  name: {{ include "opsiforce-backend.serviceName" . }}
  annotations:
    service.kubernetes.io/topology-mode: "Auto"
  labels:
    app: {{ include "opsiforce-backend.fullname" . }}
spec:
  ports:
    - name: api
      protocol: TCP
      port: {{ .Values.backend.containerPort }}
      targetPort: {{ .Values.backend.containerPort }}
    - name: app-proxy
      protocol: TCP
      port: {{ .Values.backend.appProxyPort | default 3002 }}
      targetPort: {{ .Values.backend.appProxyPort | default 3002 }}
    - name: vscode-proxy
      protocol: TCP
      port: {{ .Values.backend.vscodeProxyPort | default 3003 }}
      targetPort: {{ .Values.backend.vscodeProxyPort | default 3003 }}
  selector:
    app: {{ include "opsiforce-backend.fullname" . }}
