bifrost:
  providers:
    custom-openai-1:
      network_config:
        base_url: "https://b3bff37a-6f24-48b2-a469-142a96bc4b39.apps.dev.opsima.com/api/openai-oauth"
    custom-openai-2:
      network_config:
        base_url: "https://b3bff37a-6f24-48b2-a469-142a96bc4b39.apps.dev.opsima.com/api/openai-oauth"
    custom-openai-3:
      network_config:
        base_url: "https://b3bff37a-6f24-48b2-a469-142a96bc4b39.apps.dev.opsima.com/api/openai-oauth"
