replicaCount: 1

frontend:
  image:
    repository: ""
    tag: frontend
    pullPolicy: Always
  containerPort: 80
  resources:
    requests:
      cpu: 50m
      memory: 128Mi

imagePullSecrets:
  - name: ghcr-pull-secret
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 50m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: 80
readinessProbe:
  httpGet:
    path: /
    port: 80

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: cfke.io/region
              operator: In
              values:
                - northamerica
            - key: cfke.io/subregion
              operator: In
              values:
                - east
            - key: node.kubernetes.io/instance-type
              operator: NotIn
              values:
                - cpx11
                - cpx21
                - cpx22
                - cpx32
                - ccx13
                - cx23
                - cx33
