auth:
  username: admin
  password: dbpass1

primary:
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  extendedConfiguration: |
    log_statement = 'all'

image:
  repository: bitnamilegacy/postgresql
