apiVersion: v2
name: opsiforce-proxy
description: A Helm chart for Opsiforce proxy
type: application
version: 0.1.0
appVersion: "1.27"

dependencies:
  - name: valkey
    version: 0.9.3
    repository: https://valkey.io/valkey-helm/
    condition: valkey.enabled
