replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

proxy:
  backendService:
  frontendService:

oauth2Proxy:
  enabled: false
  image:
  clientId:
  cookieSecret:
  clientSecret:
  issuerUrl:
  logoutUrl:
  redirectUrl:
  redisPath:

valkey:
  enabled: true
  replica:
    enabled: false
  auth:
    enabled: false
  valkeyConfig: |
    notify-keyspace-events Ex
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: cfke.io/region
                operator: In
                values:
                  - northamerica
              - key: cfke.io/subregion
                operator: In
                values:
                  - east
              - key: node.kubernetes.io/instance-type
                operator: NotIn
                values:
                  - cpx11
                  - cpx21
                  - cpx22
                  - cpx32
                  - cpx31
                  - ccx13
                  - ccx23
                  - cx23
                  - cx33

imagePullSecrets:
  - name: ghcr-pull-secret
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

ingressRoute:
  enabled: true
  hostname: opsiforce.dev.opsima.com
  traefikTarget: traefik.traefik.1d27b1e1-ef9f-407a-889a-6d80fc8fdd07.northamerica-central-1a.cfke.cloudfleet.dev

resources:
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: cfke.io/region
              operator: In
              values:
                - northamerica
            - key: cfke.io/subregion
              operator: In
              values:
                - east
