replicaCount: 1

imagePullSecrets: []

auth:
  mode: static

keycloakMs:
  enabled: false

ingress:
  enabled: false

ingressRoute:
  enabled: true
  hostname: opsiforce.localtest.me
  traefikTarget: ""
  certResolver: ""

proxy:
  agentService: "http://proxy-agent:3005"
  backendService: "http://opsiforce-backend:3001"
  frontendService: "http://host.minikube.internal:8084"

appProxy:
  backendService: "proxy-app"
  backendPort: "3002"
  appsHostname: apps.opsiforce.localtest.me
  previewAppsHostname: preview.apps.opsiforce.localtest.me

vscodeProxy:
  backendService: "proxy-vscode"
  appsHostname: code.opsiforce.localtest.me

dbProxy:
  backendService: "proxy-db"
  appsHostname: db.opsiforce.localtest.me

bifrostDashboard:
  enabled: true
  serviceName: opsiforce-bifrost
  hostname: bifrost.opsiforce.localtest.me

affinity: ~
nodeSelector: {}
tolerations: []
