replicaCount: 1

imagePullSecrets: []

ingress:
  enabled: false

ingressRoute:
  enabled: true
  hostname: opsiforce.localtest.me
  traefikTarget: ""
  certResolver: ""

proxy:
  agentService: "http://proxy-agent:3005"
  backendService: "http://opsiforce-backend:3001"
  frontendService: "http://host.minikube.internal:8084"

appProxy:
  backendService: "proxy-app"
  appsHostname: apps.opsiforce.localtest.me
  previewAppsHostname: preview.apps.opsiforce.localtest.me

vscodeProxy:
  backendService: "proxy-vscode"
  appsHostname: code.opsiforce.localtest.me

dbProxy:
  backendService: "proxy-db"
  appsHostname: db.opsiforce.localtest.me

bifrostDashboard:
  enabled: true
  serviceName: opsiforce-bifrost
  hostname: bifrost.opsiforce.localtest.me

oauth2Proxy:
  image: quay.io/oauth2-proxy/oauth2-proxy:v7.13.0
  clientId: opsiforce
  clientSecret: opsiforce
  cookieSecret: localsecretlocal
  cookieDomain: .opsiforce.localtest.me
  redirectUrl: https://opsiforce.localtest.me/oauth2/callback
  issuerUrl: http://sima-keycloak-local-service:8086/realms/sima
  logoutUrl: "http://sima-keycloak-local-service:8086/realms/sima/protocol/openid-connect/logout?id_token_hint={id_token}"
  redisPath: redis://redis-session-storage-local-master:6379/0

affinity: ~
nodeSelector: {}
tolerations: []
