replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

proxy:
  agentService:
  backendService:
  frontendService:
  keycloakMsApiBackend:
  keycloakMsAssetsBackend:

oauth2Proxy:
  image:
  clientId:
  cookieSecret:
  cookieDomain:
  clientSecret:
  issuerUrl:
  logoutUrl:
  redirectUrl:
  redisPath:

imagePullSecrets:
  - name: ghcr-pull-secret
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

ingressRoute:
  enabled: true
  hostname: ""
  traefikTarget: ""
  certResolver: letsencrypt

appProxy:
  backendService: ""
  backendPort: "3002"
  appsHostname: ""
  previewAppsHostname: ""

vscodeProxy:
  backendService: ""
  appsHostname: ""

dbProxy:
  backendService: ""
  appsHostname: ""

bifrostDashboard:
  enabled: true
  serviceName: ""
  hostname: ""

resources:
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /healthz
    port: http
readinessProbe:
  httpGet:
    path: /healthz
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: cfke.io/region
              operator: In
              values:
                - northamerica
            - key: cfke.io/subregion
              operator: In
              values:
                - east
            - key: node.kubernetes.io/instance-type
              operator: NotIn
              values:
                - cpx11
                - cpx21
                - cpx22
                - cpx32
                - ccx13
                - cx23
                - cx33
